local data = {
    {"Name an object people listen to music on", "Beats headphones"},
    {"Name a popular soda", "Monster energy drink"},
    {"Name a sport that uses a ball", "American football"},
    {"Name something you would bring to the beach", "Tanning lotion"},
    {"Name something you would find in a pencil case:", "Graphing calculator"},
    {"Name a hamburger topping", "American cheese"},
    {"Name a member of the scooby doo gang", "Norville Rogers"},
    {"Name a billionare", "Francoise Bettencourt Meyers"},
    {"Name an object you use to eat food", "Butter knife"},
    {"Name a popular holiday", "Saintpatricksday"},
    {"Name something you would find in a bedroom", "Phonecharger"},
    {"Name a color of the rainbow", "Magenta"},
    {"Name something you would keep in the freezer", "Icecreamsandwiches"},
    {"Name a natural disaster", "Volcaniceruption"},
    {"Name a type of candy", "Bertiebottseveryflavourbeans"},
    {"Name a thing that is cold", "Chocolateicecream"},
    {"Name a school subject", "Differentialeuations"},
    {"Name something you would see in the ocean", "Continentalfaultlines"},
    {"Name a place you can swim", "Publicswimmingpool"},
    {"Name a nut", "Marconaalmond"},
    {"Name something you can climb", "Jomolharichomolhari"},
    {"Name a place you have to wait", "Unemploymentoffice"},
    {"Name a type of juice", "Watermelonjuice"},
    {"Name something you use to tell time", "Grandfatherclock"},
    {"Name a room in a house", "Masterbedroom"},
    {"Name a shape", "Rectangularprism"},
    {"Name a car color", "Metallicgasolinebluegreen"},
    {"Name a plant from plant vs- zombies", "Reverserepeater"},
    {"Name a us state", "Northcarolina"},
    {"Name a friendly minecraft mob", "Villager"},
    {"Name a precious gem", "Mountsainthelensemerald"},
    {"Name a character from despicable me", "Scarletoverkill"},
    {"Name one of the seven wonders of the world", "the mausoleum at halicarnassus"},
    {"Name a character from phineas and ferb", "doctor heinz doofenshmirtz"},
    {"Name an ethnicity", "Pacificislander"},
    {"Name an outdoor activity that is not a sport", "Mountainclimbing"},
    {"Name something you would see in a cave", "Caveanimals"},
    {"Name a block in minecraft", "cracked polished black stone bricks"},
    {"Name something you keep in the car", "Driverslicense"},
    {"Name a sport", "Americanfootball"},
    {"Name a place where you have to be quiet", "Doctorsoffice"},
    {"Name a type of bear", "North American Black Bear"},
    {"Name something you would find in a living room", "Flatscreentelevision"},
    {"Name a house in hogwarts", "Gryffindor"},
    {"Name one of the seven dwarfs from Snow White", "Bashful"},
    {"Name a star wars movie", "Theempiresttrikesback"},
    {"Name a periodic table element", "rutherfordium"},
    {"Name one of the ten longest rivers in the world", "Mississippiriver"},
    {"Name a country involved in wwii", "Unitedstatesofamerica"},
    {"Name a god from greek mythology", "Harpocrates"},
    {"Name something you wear on your feet", "Runningshoes"},
    {"Name a character from cars", "Dinocotransporthelicopter"},
    {"Name a skittle color", "Brightyellow"},
    {"Name an animal", "Rubythroatedhummingbird"},
    {"Name a musical instrument", "Electricguitar"},
    {"Name a disney movie", "the chronicles of narnia the lion the witch and the wardrobe"},
    {"Name a popular breakfast food", "Frenchtoaststicks"},
    {"Name something you would see on the road", "Emergencyresponsevehicles"},
    {"Name a character from sonic the hedgehog", "Knucklestheechidna"},
    {"Name something you would see at a playground", "Drinkingfountain"},
    {"Name a month in the year", "September"},
    {"Name something you would sit on", "Foldablechairs"},
    {"Name something you would bring on a camping trip", "Grahamcrackes"},
    {"Name something sharp", "Samuraisword"},
    {"Name a type of cake", "Strawberryshortcake"},
    {"Name something you keep in a wallet", "Driverslicense"},
    {"Name a fruit", "Americanelderberry"},
    {"Name a popular board game", "monopoly electronic banking edition"},
    {"Name a vegetable", "Brusselsprout"},
    {"Name a farmyard animal", "Herdingdog"},
    {"Name an ice cream flavor", "Chocolatechipcookiedough"},
    {"Name a popular youtuber", "Kids Channel India Hindi Rhymes And Baby Songs"},
    {"Name a game console", "Super Nintendo Entertainment System"},
    {"Name a pizza topping", "Roasted Green Pepper"},
    {"Name a car brand", "Acura Honda Motor Company"},
    {"Name a popular roblox game", "Natural Disaster Survival"},
    {"Name a piece of clothing", "Long Sleeve Shirt"},
    {"Name a breed of dog", "Cavalier King Charles Spaniel"},
    {"Name a character from harry potter", "Kingsley Shacklebolt"},
    {"Name a country in north america", "Saint Vincent And The Grenadines"},
    {"Name a state of matter", "Bose Einstein Condensate"},
    {"Name a flightless bird", "African Ostrich"},
    {"Name one of santa's reindeer", "Rudolph"},
    {"Name a potato chip flavor", "Cheddar and sour cream"},
    {"Name a fast food restaurant", "Kentucky Fried Chicken"},
    {"Name one of the powerpuff girls", "Buttercup"},
    {"Name a day of the week", "Wednesday"},
    {"Name a popular video game", "starwars knights of the old republic ii the sith lords"},
    {"Name a character from the simpsons", "superintendent chalmers"},
    {"Name a pokemon", "mega charizard x"},
    {"Name a country in asia", "united arab emirates"},
    {"Name a phobia", "hippopotomonstrosesquippedaliophobia"},
    {"Name a water sport", "standup paddleboarding"},
    {"Name an emotion you feel (i feel---)", "full of anticipation"},
    {"Name a country in africa", "democratic republic of the congo"},
    {"Name a boys name that starts with l:", "leonardo"},
    {"Name a u.s. state", "massachusetts"},
    {"Name a body part", "gluteus maximus"},
    {"Name a sport that can only be played indoors", "figure skating"},
    {"Name a time zone", "puerto rico and U.S. virgin islands time"},
    {"Name a consumable from fortnite", "oceans bottomless chug-jug"},
    {"Name something that lives in a shell", "snapping turtle"},
    {"Name a character from the batman comics", "commissioner james gordon"},
    {"Name a phone brand", "straight talk"},
    {"Name something you would find in the living room", "flat screen television"},
    {"Name a monster from my singing monsters", "hippityhop"},
    {"Name a u.s. president", "barack hussien obama the second"},
    {"Name an overwatch character", "junker queen"},
    {"Name a country in south america", "argentina"},
    {"Name a character from family guy", "marguerite pewterschmidt"},
    {"Name something you would find in a desert", "rattlesnake"},
    {"Name one of the seven deadly sins", "gluttony"},
    {"Name a pixar movie", "monsters university"},
    {"Name a branch of the u.s. military", "coast guard"},
    {"Name a character from finding nemo", "philip sherman"},
    {"Name an edible meat", "ground beef"},
    {"Name a character from charlie brown", "little red haired girl"},
    {"Name an animal that has a horn", "scimitar horned oryx"},
    {"Name a common superpower", "super strength"},
    {"Name a food that is usually eaten on thanksgiving", "sweet potato casserole"},
    {"Name a disney princess", "vanellope von schweetz"},
    {"Name something you would find in outer space", "international space station"},
    {"Name a planet in our solar system", "jupiter"},
    {"Name an anime", "doraemon nobita and the new steel troops"},
    {"Name a character from frozen", "anna of arendelle"},
    {"Name one of the oceans in the world", "southern ocean"},
    {"Name a country in europe", "north macedonia"},
    {"Name a type of cheese", "parmigiano reggiano"},
    {"Name a movie streaming platform", "disney plus"},
    {"Name a human organ", "large intestine"},
    {"Name a religon", "bushongo mythology"},
    {"Name something you charge regularly", "nintendo switch"},
    {"Name a type of snake", "western diamond black rattlesnake"},
    {"Name a character from spongebob squarepants", "spongebob squarepants"},
    {"Name a character from adventure time", "ancient psychic tandem war elephant"},
    {"Name a character you would see at disneyworld", "beauty and the beast"},
    {"Name a teenage mutant ninja turtle", "michel angelo"},
    {"Name a summer sport", "one-hundred meter sprint"},
    {"Name something you would find in a kitchen", "garbage disposal"},
    {"Name one of the top 100 christmas movies", "national lampoon's christmas vacation"},
    {"Name something in a salad", "Italian dressing"},
    {"Name a month with 31 days", "december"},
    {"Name a girls name that starts with a:", "alexandria"},
    {"Name a punctuation symbol", "exclamation mark"},
    {"Name a popular breakfast cereal", "fruit fibre dates walnuts and oats"},
    {"Name something you would eat at a movie theater", "bertie botts every flavour beans"},
    {"Name a character from super mario", "baby princess rosalina"},
    {"Name a famous war", "sierra leone civil war"},
    {"Name one of the four seasons", "winter"},
    {"Name something that has roots", "medium density fibreboard"},
    {"Name a social media platform", "facebook messenger"},
    {"Name a country involved in wwi", "united arab emirates (UAE)"},
    {"Name a character from diary of a wimpy kid", "rowley jefferson"},
    {"Name a programming language", "euslisp robot programming language"},
    {"Name an m&m color", "yellow"},
    {"Name something you would do in the snow", "go snowboarding"},
    {"Name a popular christmas song", "what can you get a wookiee for christmas when he already owns a comb"},
    {"Name a type of candy", "bertie botts every flavour beans"},
    {"Name a girls name that starts with m:", "maddison beer"},
    {"Name a popular swimming stroke", "breast stroke"},
    {"Name a popular breakfast cereal", "fruit fibre dates walnuts and oats"},
    {"Name a superhero", "the incredible hulk"},
    {"Name a currency", "united states dollar"},
    {"Name something you would find in a classroom", "Graphing calculator"}
}

return data
